create table if not exists public.voice_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  transcript text not null,
  translation text not null,
  target_language text not null,
  created_at timestamptz not null default now()
);

alter table public.voice_entries enable row level security;

create policy "Users can read their own voice entries"
  on public.voice_entries
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own voice entries"
  on public.voice_entries
  for insert
  with check (auth.uid() = user_id);
